/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author marquis
 */
public class TaskPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaskPanel
     */
    JFrame jf;
    ResultSet rs;
    public TaskPanel(JFrame jfrm, ResultSet rsltst) { //hopefully, rsltst will keep it's pointer's position
        this.jf = jfrm;
        this.rs = rsltst;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        try {
            Title = new javax.swing.JLabel();
            jScrollPane2 = new javax.swing.JScrollPane();
            Description = new javax.swing.JTextArea();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            created = new javax.swing.JLabel();
            started = new javax.swing.JLabel();
            ended = new javax.swing.JLabel();
            dueDate = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            progress = new javax.swing.JLabel();
            taskType = new javax.swing.JLabel();
            priority = new javax.swing.JLabel();
            timeframe = new javax.swing.JLabel();
            returnButton = new javax.swing.JButton();
            editButton = new javax.swing.JButton();
            jLabel9 = new javax.swing.JLabel();
            genre = new javax.swing.JLabel();
            markDownButton = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();

            jButton1.setText("jButton1");

            rs.first();
            String ttl = rs.getString("TITLE");
            Title.setText(ttl);

            rs.first();
            String dscrptn = rs.getString("DESCRIPTION");
            Description.setColumns(20);
            Description.setRows(5);
            Description.setText(dscrptn);
            jScrollPane2.setViewportView(Description);

            jLabel1.setText("Created:");

            jLabel2.setText("Started:");

            jLabel3.setText("Completed:");

            jLabel4.setText("Due Date:");

            rs.first();
            String crtd = rs.getString("CREATED");
            if (crtd.isBlank()) {crtd = "Does not exist.";}
            created.setText(crtd);

            rs.first();
            String strtd = rs.getString("STARTED");
            if (strtd.isBlank()) {strtd = "Does not exist.";}
            started.setText(strtd);

            rs.first();
            String ndd = rs.getString("ENDED");
            if (ndd.isBlank()) {ndd = "Does not exist.";}
            ended.setText(ndd);

            rs.first();
            String ddt = rs.getString("DUEDATE");
            if (ddt.isBlank()) {ddt = "Does not exist.";}
            dueDate.setText(ddt);

            jLabel5.setText("Progress:");

            jLabel6.setText("Priority:");

            jLabel7.setText("Timeframe:");

            jLabel8.setText("Task Type");

            rs.first();
            String cmplt = rs.getString("COMPLETENESS");
            if (cmplt.isBlank()) {cmplt = "N/A";}
            progress.setText(cmplt);

            rs.first();
            String ctgr = rs.getString("CATEGORY");
            if (ctgr.isBlank()) {ctgr = "N/A";}
            taskType.setText(ctgr);

            rs.first();
            String prrt = rs.getString("PRIORITY");
            if (prrt.isBlank()) {prrt = "N/A";}
            priority.setText(prrt);

            rs.first();
            String tmfrm = rs.getString("TIMEFRAME");
            if (tmfrm.isBlank()) {tmfrm = "N/A";}
            timeframe.setText(tmfrm);
        } catch ( Exception e ) {
            System.err.println( e.getClass().getName() + ": " + e.getMessage() );
            System.exit(0);}

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Genre:");

        genre.setText("jLabel10");

        markDownButton.setText("Markdown");
        markDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markDownButtonActionPerformed(evt);
            }
        });

        jButton2.setText("View Sub-Tasks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dueDate)
                            .addComponent(ended)
                            .addComponent(started)
                            .addComponent(created)
                            .addComponent(genre)
                            .addComponent(timeframe)
                            .addComponent(taskType)
                            .addComponent(progress)
                            .addComponent(priority)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(markDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(created)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(started)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ended)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dueDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priority)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeframe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taskType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editButton)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnButton)
                            .addComponent(markDownButton))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        JFrame fr = new JFrame("CountUp Task Manager");
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        AddEditPanel dt = new AddEditPanel(fr, this.rs);
        fr.add(dt);
        fr.pack();
        fr.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        JFrame fr = new JFrame ("CountUp Task Manager");
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        StartPanel strt = new StartPanel(fr);
        fr.add(strt);
        fr.pack();
        fr.setVisible(true);
        this.jf.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void markDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markDownButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markDownButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Description;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel created;
    private javax.swing.JLabel dueDate;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel ended;
    private javax.swing.JLabel genre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton markDownButton;
    private javax.swing.JLabel priority;
    private javax.swing.JLabel progress;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel started;
    private javax.swing.JLabel taskType;
    private javax.swing.JLabel timeframe;
    // End of variables declaration//GEN-END:variables
}
