CREATE TABLE PRIORITY (
	REFID INTEGER PRIMARY KEY,
	TITLE VARCHAR(16) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRIMARY KEY REFID,
	UNIQUE KEY TITLE
);

INSERT INTO PRIORITY (TITLE, DESCRIPTION)
	VALUES
	('Major', "Mandates completion."),
	('Medium', "A regular to-do item."),
	('Minor', "Not immenently important.");

CREATE TABLE TIMEFRAME (
	REFID INTEGER PRIMARY KEY,
	TITLE VARCHAR(16) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRIMARY KEY REFID,
	UNIQUE KEY TITLE
);

INSERT INTO TIMEFRAME (TITLE, DESCRIPTION)
	VALUES
	('Short Term', "A more immediate concern."),
	('Medium Term', "Should be completed within a season."),
	('Long Term', "A year or more may pass before this is completed.");

CREATE TABLE GENRE (
	REFID INTEGER PRIMARY KEY,
	TITLE VARCHAR(16) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRIMARY KEY REFID,
	UNIQUE KEY TITLE
);

INSERT INTO GENRE (TITLE, DESCRIPTION)
	VALUES
	('Coding', "Anything for our computer overlords."),
	('Writing', ""),
	('Design', ""),
	('Chores', ""),
	('Entertainment', ""),
	('Learning', ""),
	('Vocation', ""),
	('Handiwork', ""),
	('Seasonal', "");

CREATE TABLE TASKTYPE (
	REFID INTEGER PRIMARY KEY,
	TITLE VARCHAR(16) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRIMARY KEY REFID,
	UNIQUE KEY TITLE
);

INSERT INTO TASKTYPE (TITLE, DESCRIPTION)
	VALUES
	('Requirement', "Something needed to complete the task."),
	('Step', "One thing to do on the way to finishing."),
	('Description', "Better explains the task."),
	('Reference', "Refer back to this for help."),
	('Unexpected', "Anything that was not expected before the task was begun.");

CREATE TABLE PROGRESS (
	REFID INTEGER PRIMARY KEY,
	TITLE VARCHAR(16) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRIMARY KEY REFID,
	UNIQUE KEY TITLE
);

INSERT INTO PROGRESS (TITLE, DESCRIPTION)
	VALUES
	('Not Started', "Get moving, bud."),
	('In Progress', "Hey! I'm working on it!"),
	('Completed', "Done. Don't worry about it."),
	('Under Review', "We're suspicious of your work."),
	('Recurring', "This pesky task is very needy.");

-- default, unassigned values. Wanted to set as 0, but auto_increment
-- starts at 1.
INSERT INTO PROGRESS (REFID, TITLE, DESCRIPTION)
	VALUES (0, 'Unassigned', "Hasn't been determined.");

INSERT INTO PRIORITY (REFID, TITLE, DESCRIPTION)
	VALUES (0, 'Unassigned', "Hasn't been determined.");
	
INSERT INTO TIMEFRAME (REFID, TITLE, DESCRIPTION)
	VALUES (0, 'Unassigned', "Hasn't been determined.");

INSERT INTO TASKTYPE (REFID, TITLE, DESCRIPTION)
	VALUES (0, 'Unassigned', "Hasn't been determined.");
	
INSERT INTO GENRE (REFID, TITLE, DESCRIPTION)
	VALUES (0, 'Unassigned', "Hasn't been determined.");

CREATE TABLE TASK (
	TASKID INTEGER PRIMARY KEY,
	TITLE VARCHAR(32),
	PARENTID INT, -- NOT NEEDED FOR HISTORY
	TIMEFRAME INT NOT NULL,
	GENRE INT NOT NULL,
	PRIORITY INT NOT NULL,
	PROGRESS INT NOT NULL,
	TASKTYPE INT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	CREATEDDATE DATE NOT NULL, -- NOT NEEDED FOR HISTORY
	STARTEDDATE DATE,
	COMPLETED DATE,
	DUEDATE DATE,
	PRIMARY KEY TASKID,
	UNIQUE KEY (TITLE, PARENTID),
	FOREIGN KEY PARENTID REFERENCES TASK(TASKID),
	FOREIGN KEY TIMEFRAME REFERENCES TIMEFRAME(REFID),
	FOREIGN KEY PRIORITY REFERENCES TIMEFRAME(REFID),
	FOREIGN KEY PROGRESS REFERENCES PROGRESS(REFID),
	FOREIGN KEY TASKTYPE REFERENCES TASKTYPE(REFID),
	FOREIGN KEY GENRE REFERENCES GENRE(REFID)
);

CREATE TABLE TASKHISTORY (
	TASKID INTEGER PRIMARY KEY,
	UPDATEDDATE TIMESTAMP,
	TITLE VARCHAR(32),
	TIMEFRAME INT NOT NULL,
	GENRE INT NOT NULL,
	PRIORITY INT NOT NULL,
	PROGRESS INT NOT NULL,
	TASKTYPE INT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	STARTEDDATE DATE,
	COMPLETED DATE,
	DUEDATE DATE,
	PRIMARY KEY (TASKID, TIMESTAMP),
	FOREIGN KEY TASKID REFERENCES TASK(TASKID)
	FOREIGN KEY TIMEFRAME REFERENCES TIMEFRAME(REFID),
	FOREIGN KEY PRIORITY REFERENCES TIMEFRAME(REFID),
	FOREIGN KEY PROGRESS REFERENCES PROGRESS(REFID),
	FOREIGN KEY TASKTYPE REFERENCES TASKTYPE(REFID),
	FOREIGN KEY GENRE REFERENCES GENRE(REFID)
);
