-- populate tables with test data
INSERT INTO TASK (TASKID, TITLE, DESCRIPTION, CREATED, STARTED, ENDED, DUEDATE, CATEGORY, COMPLETENESS, PRIORITY, TIMEFRAME)
VALUES
	(1, 'CountUp Task Manager', "A task manager that helps you count up all the tasks you've completed.", CURRENT_TIMESTAMP,
	'2020-07-25 00:00:01', null, '2020-12-31 23:59:59', 2, 3, 2, 2),
	(2, 'Moorlands', "Novel idea for writing a novel.", CURRENT_TIMESTAMP-10, '2018-06-01 12:00:00', null, null, 10, 3, 1, 3),
	(3, 'Car fixes', "Gotta fix up the car", CURRENT_TIMESTAMP-5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP+5, CURRENT_TIMESTAMP+3,
	4, 1, 3, 1);

INSERT INTO DETAIL (TASKID, DETAIL_CATEGORY, STEP_NUMBER, DESCRIPTION, CREATED, STEP_DUEDATE, STEP_STARTED, STEP_DONE)
VALUES
	(1, 2, 1, "create documentation", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP-900, CURRENT_TIMESTAMP-1000, CURRENT_TIMESTAMP-901),
	(1, 2, 2, "create database", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP-800, CURRENT_TIMESTAMP-900, CURRENT_TIMESTAMP-801),
	(1, 2, 3, "finish all the rest", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP-700, CURRENT_TIMESTAMP-800, CURRENT_TIMESTAMP-701),
	(2, 8, null, "procrastination", CURRENT_TIMESTAMP, null, null, null);
